version: "3.8"


services:

  db_1:
    image: postgres
    container_name: vlad
    environment:
      - POSTGRES_DB = root
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD=286226
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A drfsite worker -l INFO
    volumes:
      - .:/router/router_2/router_3/drfsite/
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1[::1]
      - DJANGO_BROKER=redis://localhost:6379/0
      - DJANGO_BACKEND=redis://localhost:6379/0
    depends_on:
      - django
      - redis
  django:
    build: .
    restart: always
    container_name: django_room
    command: python drfsite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/router/router_2/router_3/drfsite/
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB = root
      - POSTGRES_USER = root
      - POSTGRES_PASSWORD=286226
    depends_on:
      - db_1
      - redis

volumes:
  pgdata: